name: billcare
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+5

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.0.0
  firebase_messaging: ^16.0.0
  flutter_local_notifications: ^19.4.0
  intl: ^0.20.2
  shared_preferences: ^2.5.3
  flutter_secure_storage: ^10.0.0
  pdf: ^3.11.3
  printing: ^5.14.2
  url_launcher: ^6.3.2
  image_picker: ^1.1.2
  share_plus: ^11.1.0
  uuid: ^4.5.1
  path_provider: ^2.1.5
  collection: ^1.19.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  background_color: "#0xFF1E3A8A"
  uses-material-design: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/
